name: goreleaser-fleet-support-kubequery

on:
  push:
    tags:
      - "*-support-kubequery"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: Docker Hub
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Needed for goreleaser

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - name: Install JS Dependencies
        run: make deps-js

      - name: Install Go Dependencies
        run: make deps-go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f .goreleaser-keepwn.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
